### ISSUE TITLE
Screen Redesign

### ISSUE THREAD

**Issue by fabio-gustav** [Illinois-State-Solar-Car/Driver-Screen#4]
V2 redesign of the screen with circuitpython and single pin headers

**Comment by Austin8462** [comment]
Found a potential option for [Deutsch connector replacement.](https://www.te.com/usa-en/product-DT13-08PC.html) for the PCB side of things. -- 8 pin (2x4) which is fine since with our current D9 connector, we have duplicate pins.

**Comment by Austin8462** [comment]
After looking through EasyEDA more, there is not much in the library for 8 pin Deutsch compared to [12 pin connector -](https://www.te.com/usa-en/product-DTF13-12PC.html)- switching to 12 pin for now.

Both connectors being considered for PCB side have been right-angled mounting due to the way they'll end up in the car to help with cable flow.

**Comment by Austin8462** [comment]
Board re-design complete & ready for review. D9 Connectors have been switched over to the 12P Deutsch and 2x 3.3v access has been added to the UART connection.

**Comment by Austin8462** [comment]
Back to In Progress - reducing overall board size

Also need to find the correct gray Deutsch connectors

**Comment by Austin8462** [comment]
Overall size of the board has been significantly reduced. Will find the correct series of Deutsch connectors at a later time.

**Comment by Austin8462** [comment]
Screen mounting holes reduced to .125in - As with DCU board, SHLD bounded to GND copper areas, SHLD GND unused as car is all one singular ground plane

Board in cart to be hopefully purchased tomorrow

**Comment by Austin8462** [comment]
Rev2 boards were ordered.

**Comment by Austin8462** [comment]
I done diddly goofed the connector sizing....
